### ISSUE TITLE
使用zapier+airtable识别不了PIN

### ISSUE THREAD

**Issue by ttt789-ppo** [bitsavers/eu_ex#3]
<img width="540" alt="屏幕截图 2022-03-17 220457" src="https://user-images.githubusercontent.com/72877282/158826612-b1808108-4f74-467a-8c73-9aa6d2461858.png">

**Comment by ttt789-ppo** [comment]
那个邮件是一整块的，它选不到里面的PIN，然后运行也是读出来的PIN是整块的内容

**Comment by ttt789-ppo** [comment]
<img width="626" alt="屏幕截图 2022-03-17 220559" src="https://user-images.githubusercontent.com/72877282/158827294-ca91d454-57b1-46f1-89d3-92c75adef0d8.png">

**Comment by ZetaoYang** [comment]
zapier mail paser 里 你得设置规则把 pin 解析出来啊。

**Comment by ttt789-ppo** [comment]
> zapier mail paser 里 你得设置规则把 pin 解析出来啊。

可是我不会，我是看教程的那种小白，我再摸索一下吧

**Comment by ZetaoYang** [comment]
https://github.com/bitsavers/eu_ex/blob/main/docs/ZapierAirtable.md 文档已更，希望有帮助

**Comment by ttt789-ppo** [comment]
> https://github.com/bitsavers/eu_ex/blob/main/docs/ZapierAirtable.md 文档已更，希望有帮助

非常感谢
