### ISSUE TITLE
登录PIN提示This PIN is invalid.

### ISSUE THREAD

**Issue by ttt789-ppo** [bitsavers/eu_ex#4]
euserv好像把PIN改成数字PIN了，而且填对了PIN还是不能登录，提示This PIN is invalid，从这两天开始的，我手动登录了一下，把发过来的PIN填进去，发现也是登录不了
![Screenshot_2022-04-04-08-56-30-401_com miui home](https://user-images.githubusercontent.com/72877282/161458110-663ec911-68d2-402f-9b83-b4f16370e50f.jpg)
![Screenshot_2022-04-04-08-56-56-967_nekox messenger](https://user-images.githubusercontent.com/72877282/161458113-b77778b5-7419-4eca-b586-3e56b9855cb5.jpg)

**Comment by ZetaoYang** [comment]
从 2022 年 4 月 2 日开始就是这个情况，应该是 EUserv 生成 PIN 码的程序出现故障了。正常的 login PIN 应该是数字+字母的全大写五位混合，而 renew PIN 才是五位全数字。https://support.euserv.com 的版本仍然是 `EUserv KundenCenter (2.17.1_20220228)`
![image](https://user-images.githubusercontent.com/10769951/161458878-778ed90c-e204-43b6-874c-a2c1d861471f.png)

现在手工登录也是这个情况，login PIN 不对，然后登录不了。

**Comment by ZetaoYang** [comment]
现在(2022 年 4 月 4日)已恢复, login PIN 已经是五位纯数字了。
