### ISSUE TITLE
Please Add Serverless Cloud Function Support

### ISSUE THREAD

**Issue by baby9** [bitsavers/eu_ex#6]
TencentCloud changed their SFC price a few months ago, but AlibabaCloud is still free of charge with limited quota. So is HuaweiCloud, which means we could deploy application on  AlibabaCloud SFC or HuaweiCloud SFC

**Comment by ZetaoYang** [comment]
https://github.com/bitsavers/eu_ex#how-to-run
https://github.com/bitsavers/eu_ex#dependencies
here it is,
> AWS Lambda function handler name: `main.lambda_handler`

> If you deploy it as a severless function, e.g. AWS Lambda, you need to package the dependencies along with the source code.

I have never used AlibabaCloud, TencentCloud and HuaweiCloud. You can refer to the deployment steps here https://github.com/o0oo0ooo0/EUserv_extend/blob/main/README.md.

**Comment by baby9** [comment]
> https://github.com/bitsavers/eu_ex#how-to-run https://github.com/bitsavers/eu_ex#dependencies here it is,
> 
> > AWS Lambda function handler name: `main.lambda_handler`
> 
> > If you deploy it as a severless function, e.g. AWS Lambda, you need to package the dependencies along with the source code.
> 
> I have never used AlibabaCloud, TencentCloud and HuaweiCloud. You can refer to the deployment steps here https://github.com/o0oo0ooo0/EUserv_extend/blob/main/README.md.

OK, I will try. Anyway, Thank you.
